import pic1 from "./imagenes-item/detergente.png"
import pic2 from "./imagenes-item/limpiavidrios.png"
import pic3 from "./imagenes-item/desinfeccion.png"
import pic4 from "./imagenes-item/escoba.png"
import pic5 from "./imagenes-item/trapoPiso.png"
import pic6 from "./imagenes-item/esponja.png"
import pic7 from "./imagenes-item/guantes.png"
import pic8 from "./imagenes-item/lavandina.png"
import pic9 from "./imagenes-item/escobilla.png"
import pic10 from "./imagenes-item/paño.png"
import pic11 from "./imagenes-item/spray.png"
import pic12 from "./imagenes-item/spray2.png"
import pic13 from "./imagenes-item/jabon-liquido.png"
import pic14 from "./imagenes-item/desodorantepiso.png"

export default { pic1, pic2, pic3, pic4, pic5, pic6, pic7, pic8, pic9, pic10, pic11, pic12, pic13, pic14 }